/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerMeGuie;
import javax.swing.ImageIcon;
import model.Hotel;

/**
 *
 * @author Samuel
 */
public class CadastroHotel extends javax.swing.JFrame {
    static ImageIcon starOn = new ImageIcon("E:/IFBA/2019.2/LP2/MeGuie/icon/starOn.png");
    static ImageIcon backOff = new ImageIcon("E:/IFBA/2019.2/LP2/MeGuie/icon/backOff.png");
    static ImageIcon backOn = new ImageIcon("E:/IFBA/2019.2/LP2/MeGuie/icon/backOn.png");
    static ImageIcon starOff = new ImageIcon("E:/IFBA/2019.2/LP2/MeGuie/icon/starOff.png");
    
    private int star;
    /**
     * Creates new form CadastroHotel
     */
    public CadastroHotel() {
        initComponents();
        this.setLocationRelativeTo(rootPane);
        
        lblVoltar.setIcon(backOff);
        rdStar1.setIcon(starOff);
        rdStar2.setIcon(starOff);
        rdStar3.setIcon(starOff);
        rdStar4.setIcon(starOff);
        rdStar5.setIcon(starOff);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblVoltar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rdSim1 = new javax.swing.JRadioButton();
        rdNao1 = new javax.swing.JRadioButton();
        rdSim2 = new javax.swing.JRadioButton();
        rdNao2 = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        txtCEP1 = new javax.swing.JTextField();
        txtCEP2 = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        rdStar1 = new javax.swing.JRadioButton();
        rdStar2 = new javax.swing.JRadioButton();
        rdStar3 = new javax.swing.JRadioButton();
        rdStar4 = new javax.swing.JRadioButton();
        rdStar5 = new javax.swing.JRadioButton();
        btnCadastrar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVoltarMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("MeGuie");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastrar Hotel");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CEP:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("-");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Estrela:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Preço:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ar-Condicionado:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Café da Manhã:");

        rdSim1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdSim1);
        rdSim1.setText("Sim");
        rdSim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSim1ActionPerformed(evt);
            }
        });

        rdNao1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdNao1);
        rdNao1.setText("Não");

        rdSim2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rdSim2);
        rdSim2.setText("Sim");

        rdNao2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rdNao2);
        rdNao2.setText("Não");

        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });

        rdStar1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdStar1);
        rdStar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdStar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdStar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rdStar1MouseExited(evt);
            }
        });

        rdStar2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdStar2);
        rdStar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdStar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rdStar2MouseEntered(evt);
            }
        });

        rdStar3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdStar3);
        rdStar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdStar3MouseClicked(evt);
            }
        });
        rdStar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdStar3ActionPerformed(evt);
            }
        });

        rdStar4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdStar4);
        rdStar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdStar4MouseClicked(evt);
            }
        });

        rdStar5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdStar5);
        rdStar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdStar5MouseClicked(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Bairro:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(29, 29, 29)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rdSim2)
                                                .addComponent(rdSim1))))
                                    .addGap(34, 34, 34)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdNao1)
                                        .addComponent(rdNao2)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCEP2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBairro)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnCadastrar)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rdStar1)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdStar2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdStar3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(rdStar4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdStar5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtCEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCEP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rdStar1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rdStar2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rdStar3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rdStar5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(rdStar4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rdSim1)
                    .addComponent(rdNao1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rdSim2)
                    .addComponent(rdNao2))
                .addGap(15, 15, 15)
                .addComponent(btnCadastrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new Logado().setVisible(true);
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void lblVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseEntered
        // TODO add your handling code here:
        lblVoltar.setIcon(backOn);
    }//GEN-LAST:event_lblVoltarMouseEntered

    private void lblVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseExited
        // TODO add your handling code here:
        lblVoltar.setIcon(backOff);
    }//GEN-LAST:event_lblVoltarMouseExited

    private void rdSim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdSim1ActionPerformed

    private void rdStar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdStar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdStar3ActionPerformed

    private void rdStar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdStar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rdStar1MouseEntered

    private void rdStar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdStar1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_rdStar1MouseExited

    private void rdStar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdStar1MouseClicked
        // TODO add your handling code here:
        rdStar1.setIcon(starOn);
        rdStar2.setIcon(starOff);
        rdStar3.setIcon(starOff);
        rdStar4.setIcon(starOff);
        rdStar5.setIcon(starOff);
        star = 1;
    }//GEN-LAST:event_rdStar1MouseClicked

    private void rdStar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdStar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_rdStar2MouseEntered

    private void rdStar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdStar2MouseClicked
        // TODO add your handling code here:
        rdStar1.setIcon(starOn);
        rdStar2.setIcon(starOn);
        rdStar3.setIcon(starOff);
        rdStar4.setIcon(starOff);
        rdStar5.setIcon(starOff);
        star = 2;
    }//GEN-LAST:event_rdStar2MouseClicked

    private void rdStar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdStar3MouseClicked
        // TODO add your handling code here:
        rdStar1.setIcon(starOn);
        rdStar2.setIcon(starOn);
        rdStar3.setIcon(starOn);
        rdStar4.setIcon(starOff);
        rdStar5.setIcon(starOff);
        star = 3;
    }//GEN-LAST:event_rdStar3MouseClicked

    private void rdStar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdStar4MouseClicked
        // TODO add your handling code here:
        rdStar1.setIcon(starOn);
        rdStar2.setIcon(starOn);
        rdStar3.setIcon(starOn);
        rdStar4.setIcon(starOn);
        rdStar5.setIcon(starOff);
        star = 4;
    }//GEN-LAST:event_rdStar4MouseClicked

    private void rdStar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdStar5MouseClicked
        // TODO add your handling code here:
        rdStar1.setIcon(starOn);
        rdStar2.setIcon(starOn);
        rdStar3.setIcon(starOn);
        rdStar4.setIcon(starOn);
        rdStar5.setIcon(starOn);
        star = 5;
    }//GEN-LAST:event_rdStar5MouseClicked

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        ControllerMeGuie controller = new ControllerMeGuie();
        Hotel hotel = new Hotel();

        String nome = txtNome.getText();
        String CEP = txtCEP1.getText().concat("-" + txtCEP2.getText());
        String bairro = txtBairro.getText();
        float preco = Float.parseFloat(txtPreco.getText());
        boolean arCondicionado = false;
        boolean cafe = false;
        
        if(rdSim1.isSelected())
            arCondicionado = true;
        else if(rdSim2.isSelected())
            arCondicionado = false;
        
        if(rdSim2.isSelected())
            cafe = true;
        else if(rdNao2.isSelected())
            cafe = false;
        
        boolean valid = controller.cadastrarHotel(star, preco, arCondicionado, cafe, nome, CEP, bairro);
        
        if(valid == true){
            setVisible(false);
            new Logado().setVisible(true);
        }else
            lblResultado.setText("Este hotel já está cadastrado!");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        // TODO add your handling code here:
        lblResultado.setText(null);
    }//GEN-LAST:event_txtNomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JRadioButton rdNao1;
    private javax.swing.JRadioButton rdNao2;
    private javax.swing.JRadioButton rdSim1;
    private javax.swing.JRadioButton rdSim2;
    private javax.swing.JRadioButton rdStar1;
    private javax.swing.JRadioButton rdStar2;
    private javax.swing.JRadioButton rdStar3;
    private javax.swing.JRadioButton rdStar4;
    private javax.swing.JRadioButton rdStar5;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP1;
    private javax.swing.JTextField txtCEP2;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
